---
- name: Install Docker
  block:

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        file: /tmp/docker.gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Wait 30 seconds
      pause:
        seconds: 30

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes
  tags:
    - install_docker