---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - build-essential
      - libpcre3-dev
      - libssl-dev
      - perl
      - make
      - curl
      - zlib1g-dev
      - lua5.1
      - libreadline-dev
      - liblua5.1-0-dev
      - unzip
      - apt-transport-https
      - ca-certificates
      - libyaml-dev
      - gnupg
      - lsb-release
    state: present
  tags:
    - install_dependencies